using MediKlaudAPI6.FormQuery;
using MediKlaudAPI6.FormQuery.Cafeteria;
using MediKlaudAPI6.Models.Cafeteria;

namespace MediKlaudAPI6.Interface.Cafeteria
{
    public interface ICafeteriaService
    {
        Task<String> getCafeteriaData(GetCafeteriaDataQuery getCafeteriaDataQuery);
        Task<String> getCafeteriaDataList(GetCafeteriaDataListQuery getCafeteriaDataListQuery);
        Task<String> addCafeteria(CafeteriaSave cafeteria);


        Task<String> getCafeteriaItemData(GetCafeteriaItemDataQuery getCafeteriaDataQuery);
        Task<String> getCafeteriaItemDataList(GetCafeteriaItemDataListQuery getCafeteriaDataListQuery);
        Task<String> addCafeteriaItem(CafeteriaItemSave cafeteria);
        Task<String> getUomList(GetAllCmbListQuery getAllCmbListQuery);
        Task<String> getManufacturerList(GetAllCmbListQuery getAllCmbListQuery);
        Task<String> getSupplierList(GetAllCmbListQuery getAllCmbListQuery);
        Task<String> getCategoryList(GetAllCmbListQuery getAllCmbListQuery);
        Task<String> getCounryList(GetAllCmbListQuery getAllCmbListQuery);
        Task<String> getAutoGenerateItemNo(GetAutoGeneratedItemNoQuery getAutoGeneratedItemNoQuery);
    }
    

  
}
